version: '3.8'
services:
  server:
    build: stats
    image: stats_server_image
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statsdb

  db:
    image:
      postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      db_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d statsdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

