DROP TABLE IF EXISTS stats;
CREATE TABLE IF NOT EXISTS stats
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    ip character varying(15),
    app character varying(50),
    created timestamp without time zone,
    url character varying(30),
    CONSTRAINT stats_pkey PRIMARY KEY (id)
)